require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlogEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # BlogEntry. As you add validations to BlogEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all blog_entries as @blog_entries" do
      blog_entry = BlogEntry.create! valid_attributes
      get :index
      assigns(:blog_entries).should eq([blog_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested blog_entry as @blog_entry" do
      blog_entry = BlogEntry.create! valid_attributes
      get :show, :id => blog_entry.id.to_s
      assigns(:blog_entry).should eq(blog_entry)
    end
  end

  describe "GET new" do
    it "assigns a new blog_entry as @blog_entry" do
      get :new
      assigns(:blog_entry).should be_a_new(BlogEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested blog_entry as @blog_entry" do
      blog_entry = BlogEntry.create! valid_attributes
      get :edit, :id => blog_entry.id.to_s
      assigns(:blog_entry).should eq(blog_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlogEntry" do
        expect {
          post :create, :blog_entry => valid_attributes
        }.to change(BlogEntry, :count).by(1)
      end

      it "assigns a newly created blog_entry as @blog_entry" do
        post :create, :blog_entry => valid_attributes
        assigns(:blog_entry).should be_a(BlogEntry)
        assigns(:blog_entry).should be_persisted
      end

      it "redirects to the created blog_entry" do
        post :create, :blog_entry => valid_attributes
        response.should redirect_to(BlogEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blog_entry as @blog_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogEntry.any_instance.stub(:save).and_return(false)
        post :create, :blog_entry => {}
        assigns(:blog_entry).should be_a_new(BlogEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogEntry.any_instance.stub(:save).and_return(false)
        post :create, :blog_entry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blog_entry" do
        blog_entry = BlogEntry.create! valid_attributes
        # Assuming there are no other blog_entries in the database, this
        # specifies that the BlogEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlogEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => blog_entry.id, :blog_entry => {'these' => 'params'}
      end

      it "assigns the requested blog_entry as @blog_entry" do
        blog_entry = BlogEntry.create! valid_attributes
        put :update, :id => blog_entry.id, :blog_entry => valid_attributes
        assigns(:blog_entry).should eq(blog_entry)
      end

      it "redirects to the blog_entry" do
        blog_entry = BlogEntry.create! valid_attributes
        put :update, :id => blog_entry.id, :blog_entry => valid_attributes
        response.should redirect_to(blog_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the blog_entry as @blog_entry" do
        blog_entry = BlogEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => blog_entry.id.to_s, :blog_entry => {}
        assigns(:blog_entry).should eq(blog_entry)
      end

      it "re-renders the 'edit' template" do
        blog_entry = BlogEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => blog_entry.id.to_s, :blog_entry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blog_entry" do
      blog_entry = BlogEntry.create! valid_attributes
      expect {
        delete :destroy, :id => blog_entry.id.to_s
      }.to change(BlogEntry, :count).by(-1)
    end

    it "redirects to the blog_entries list" do
      blog_entry = BlogEntry.create! valid_attributes
      delete :destroy, :id => blog_entry.id.to_s
      response.should redirect_to(blog_entries_url)
    end
  end

end
